apiVersion: v1
kind: Pod
metadata:
  name: oliveth-pod
  labels:
    name: oliveth-pod
spec:
  containers:
  - name: oliveth-container
    image: oliveth/oliveth-image:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"    
    ports:
      - containerPort: 80
